### ISSUE TITLE
CORS error while sign in

### ISSUE THREAD

**Issue by vidhanshu** [ShivaBhattacharjee/Muxik#6]
**Describe the bug**
Sign up gives CORS error

**To Reproduce**
1. Just try to sign up: [https://muxik.netlify.app/sign-up](https://muxik.netlify.app/sign-up)

**Expected behavior**
Should be able to sign up successfully, if not already

**Screenshots**
![image](https://github.com/ShivaBhattacharjee/Muxik/assets/84308141/a2bf424b-7961-4fa1-ab00-005a496a8633)

**Comment by ShivaBhattacharjee** [comment]
Actually i have updated the backend api for signup so its broken for the time being it will be fixed once i migrate to nextjs
